=begin

This is auto-generated class by sdk-generator 

=end

# All files
require File.expand_path( '../avalara_sdk/api_client.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api_error.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/A1099/V2/companies_w9_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/A1099/V2/forms_w9_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/A1099/V2/forms1099_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/A1099/V2/issuers1099_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/A1099/V2/jobs1099_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/EInvoicing/V1/data_input_fields_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/EInvoicing/V1/documents_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/EInvoicing/V1/interop_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/EInvoicing/V1/mandates_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/EInvoicing/V1/subscriptions_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/api/EInvoicing/V1/trading_partners_api.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/auth/device_authorization_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/auth/oauth_helper.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/auth/token_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/configuration.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/attribute.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/authorized_api_request_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/authorized_api_request_v2_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/base_company_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/base_form_list_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/bulk_upsert1099_forms_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/company_create_update_request_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/company_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/company_response_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/company_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/data.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/error_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/error_response_errors_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/error_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form_request_base.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form_request_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form_response_base.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form_single_request_base.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_base.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_div_list_item.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_div_list.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_div_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_k_list_item.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_k_list.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_k_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_k.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_list_data_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_list.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_misc_list_item.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_misc_list.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_misc_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_misc.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_nec_list_item.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_nec_list.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_nec_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_nec.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_proccess_result.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_r_list_item.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_r_list.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_r_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_r.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/form1099_status_detail.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/http_validation_problem_details.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/i_create_form1099_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/i_update_form1099_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/issuer_command.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/issuer_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/iw9_form_data_models_one_of.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/job_result.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/link.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/paginated_query_result_model_company_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/paginated_query_result_model_issuer_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/paginated_query_result_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/paginated_w9_forms_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/problem_details.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/state_and_local_withholding_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/state_and_local_withholding.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/state_efile_status_detail.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/substantial_us_owner_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/validation_error.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w4_form_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w4_form_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_ben_e_form_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_ben_e_substantial_us_owner_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_ben_form_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_ben_form_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_bene_form_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_imy_form_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w8_imy_form_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w9_form_base_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w9_form_data_model.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/A1099/V2/w9_form_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/bad_download_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/bad_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/batch_search_list_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/batch_search_participants202_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/batch_search.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/conditional_for_field.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/data_input_field_not_used_for.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/data_input_field_optional_for.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/data_input_field_required_for.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/data_input_field.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/data_input_fields_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/directory_search_response_value_inner_addresses_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/directory_search_response_value_inner_identifiers_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/directory_search_response_value_inner_supported_document_types_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/directory_search_response_value_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/directory_search_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_fetch_request_data_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_fetch_request_metadata.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_fetch_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_fetch.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_list_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_status_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_submission_error.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_submit_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/document_summary.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/error_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/event_id.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/event_message.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/event_payload.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/event_subscription.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/fetch_documents_request_data_inner.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/fetch_documents_request_metadata.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/fetch_documents_request.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/forbidden_error.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/hmac_signature_value.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/hmac_signature.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/id.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/input_data_formats.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/internal_server_error.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/mandate_data_input_field_namespace.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/mandate_data_input_field.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/mandate.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/mandates_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/not_found_error.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/not_used_for_field.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/output_data_formats.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/pagination.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/required_when_field.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/signature_signature.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/signature_value_signature.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/signature_value.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/signature.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/status_event.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/submit_document_data.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/submit_document_metadata.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/submit_interop_document202_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/subscription_common.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/subscription_detail.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/subscription_list_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/subscription_registration.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/success_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/webhook_invocation.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/webhooks_error_info.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/webhooks_error_response.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/models/EInvoicing/V1/workflow_ids.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/response_hash.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/token_metadata.rb', __FILE__) 
require File.expand_path( '../avalara_sdk/version.rb', __FILE__) 


module AvalaraSdk
  class << self
    # Customize default settings for the SDK using block.
    #   AvalaraSdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
